### PR TITLE
Discord ID grabbed automatically

### LINKED ISSUE #13: Gather Discord IDs automatically

### LINKED ISSUE #16: no validation on discord ID
https://github.com/aracred/AraCred/runs/600313413?check_suite_focus=true#step:5:94

someone entered their discord ID incorrectly, as this is being uploaded directly to the `project.json` file, it is breaking the workflow and causing SC to fail. 
TODO: 
- [ ] add validation to discord id input

### PR DESCRIPTION
**Pull request by crisog**
When signing up, the bot will automatically grab the discord ID of the user. If the discord ID is provided, the bot will overwrite it with the correct one.

Closes #13 and Closes #16

### CODE REVIEW

File: src/handlers/signup.js [hunk 1]
```diff
@@ -13,7 +13,10 @@ const GITHUB_API_URL = 'https://api.github.com'
 
 module.exports = function signup(message) {
   try {
-    const [username, platforms] = parseSignup(message.content)
+    const [username, platforms] = parseSignup(
+      message.content,
+      message.member.id,
```
Comment (Evalir) [inline src/handlers/signup.js:18]: Shouldn't this be `.author.id`? Or can we use member as well?

File: src/parser/signup.js [hunk 2]
```diff
@@ -1,4 +1,4 @@
-module.exports = function parseSignup(message) {
+module.exports = function parseSignup(message, discordId) {
```
Comment (Evalir) [inline src/parser/signup.js:1]: After adding the id, we should validate for it to not be undefined as well.

File: src/parser/signup.test.js [hunk 3]
```diff
@@ -13,6 +13,6 @@ describe('signup parameters parser 📝', () => {
   test('It properly parses and returns the parameters for signup', () =>
     expect(parseSignup('!ac signup foo github/foo')).toEqual([
       'foo',
-      ['github/foo'],
+      ['github/foo', 'discord/undefined'],
```
Comment (Evalir) [inline src/parser/signup.test.js:16]: This is not tested properly. :) We should validate that is as long as a Discord id is, and that we don't have any letters or any extraneous things on the id.

File: src/handlers/signup.js (hunk 1 above)
Comment (crisog) [reply src/handlers/signup.js:18]: We can use 'member' as well, given that it will return the same _as long as the user is also a member_ of the guild where the bot is listening. `.member.id` is read-only while `.author.id` is not.

Reference: https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=member

File: src/parser/signup.js (hunk 2 above)
Comment (crisog) [reply src/parser/signup.js:1]: Great catch, I will definitely look into this as soon as possible.

Comment (crisog) [reply src/parser/signup.js:1]: Thanks, I will definitely look into this as soon as I can.

File: src/parser/signup.js [hunk 4]
```diff
@@ -1,10 +1,16 @@
 module.exports = function parseSignup(message, discordId) {
+  
+  if (typeof discordId === 'undefined') {
```
Comment (Evalir) [inline src/parser/signup.js:3]: I believe it's better to check if it's not a string; that's the type we want. I believe Discord IDs are also of fixed length; if they are, we should do a regex check to see:
- If they're the correct length
- If they only contain numbers.

This way we avoid getting extraneous things in the ID itself.

File: src/parser/signup.test.js [hunk 5]
```diff
@@ -1,18 +1,23 @@
 const parseSignup = require('./signup')
 
+const discordId = '474405294307278880'
```
Comment (Evalir) [inline src/parser/signup.test.js:3]: This is probably someone's ID. Let's try to use a more generic one. :)

**Comment by Evalir** [comment]
Great! We know only need to do a few things:

- Test locally
- Document the help command to highlight this feature

This way we have everything up to date and can merge; Of course, if you find anything else that needs to be updated, please do!

**Comment by crisog** [comment]
> Great! We know only need to do a few things:
> 
> * Test locally
> * Document the help command to highlight this feature
> 
> This way we have everything up to date and can merge; Of course, if you find anything else that needs to be updated, please do!

I have just tested locally with a testing bot, all seems to be working just as expected. All tests passed too.

I updated the help command, let me know if it's not clear enough yet.
